layout: sidebar
style: dark
repository : palatos/palatos.github.io

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 10
  exclude:
    archived: false
    forks: true
    projects:
      - mynotes
    # - repo-name

social_media:
  googlescholar: '5qPen1YAAAAJ&view_op=list_works&sortby=pubdate'
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Explainable AI
    web_url: https://github.com/palatos/RISE_tf
    image_url: https://raw.githubusercontent.com/palatos/RISE_tf/main/examples/dog_RISE.png

  - name: Medical Imaging AI
    image_url: https://upload.wikimedia.org/wikipedia/commons/a/af/PBEosinophil.jpg
    
  - name: Generative Art
    image_url: https://i.imgur.com/BPBEDPe.png
